<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <TargetFrameworkIdentifier>.NETFramework</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <LangVersion>12.0</LangVersion>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <Title>CnCNet Launcher</Title>
    <Description>Launcher for CnCNet Client</Description>
    <Company>CnCNet</Company>
    <Product>CnCNet Client Launcher</Product>
    <Copyright>Copyright © CnCNet, Rampastring 2011-2024</Copyright>
    <Trademark></Trademark>
    <AssemblyName>Glory of the Republic</AssemblyName>
    <RootNamespace>CnCNet.LauncherStub</RootNamespace>
    <ComVisible>false</ComVisible>
    <CLSCompliant>false</CLSCompliant>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <Nullable>enable</Nullable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Platform>AnyCPU</Platform>
    <ApplicationIcon>clienticon.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="clienticon.ico" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <PropertyGroup>
      <DeployDir>C:\Users\Vampire\Desktop\AGWar1.3.0</DeployDir>
    </PropertyGroup>
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(DeployDir)" SkipUnchangedFiles="true" Condition="Exists('$(DeployDir)')" />
  </Target>
</Project>